{"name": "test_02_login", "status": "failed", "statusDetails": {"message": "AssertionError: assert 3 < 2", "trace": "def test_02_login():\n>       assert 3<2\nE       assert 3 < 2\n\ntest_request.py:10: AssertionError"}, "start": 1604845095495, "stop": 1604845095495, "uuid": "35c8a951-2a88-44c2-bb1d-e12c8f3a4ad4", "historyId": "a4ef85c776a6f72c12398de4b6e3c8d6", "testCaseId": "438ddeb5e2577384616d6bb2a2b4f99a", "fullName": "test_request#test_02_login", "labels": [{"name": "suite", "value": "test_request"}, {"name": "host", "value": "WIN-4UUDP7C921V"}, {"name": "thread", "value": "11864-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_request"}]}