{"name": "test_02_login", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 > 2", "trace": "def test_02_login():\n>       assert 1>2\nE       assert 1 > 2\n\ntest_request.py:10: AssertionError"}, "start": 1604832541661, "stop": 1604832541662, "uuid": "a672cb01-ee64-4e63-9118-fd6f140a735e", "historyId": "a4ef85c776a6f72c12398de4b6e3c8d6", "testCaseId": "438ddeb5e2577384616d6bb2a2b4f99a", "fullName": "test_request#test_02_login", "labels": [{"name": "suite", "value": "test_request"}, {"name": "host", "value": "WIN-4UUDP7C921V"}, {"name": "thread", "value": "10344-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_request"}]}